#!/bin/sh

bind -m vi-insert '"kj":vi-movement-mode'

# test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
alias ls='ls --color=auto -CF'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff --color=auto'
alias ip='ip --color=auto'

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# alias bright='sudo chmod 666 /sys/class/backlight/intel_backlight/brightness' # for Arch dualboot
alias cwd='pwd | clip.exe' # clip.exe for WSL and xclip for xorg based systems
alias hr='printf "%$(tput cols)s\n" | tr " " "-"'

alias v='nvim'
alias cls='clear'
alias apt='sudo apt'
alias nala='sudo nala'
alias npm='sudo npm'

alias dotfiles_git='/usr/bin/git --git-dir=/home/ishaan/.dotfiles/ --work-tree=/home/ishaan'

export EDITOR='vim'
export VISUAL='vim'

eval "$(zoxide init "$(echo "$SHELL" | tr '/' '\n' | tail -1)")"
alias cd='z'

[ -d "$HOME/.local/share/nvim/mason/bin/" ] && export PATH="$HOME/.local/share/nvim/mason/bin/:$PATH"
[ -d "/usr/local/cuda-12.2/bin/" ] && export PATH="/usr/local/cuda-12.2/bin/:$PATH"
[ -d "/usr/local/cuda-12.2/lib64/" ] && export LD_LIBRARY_PATH="/usr/local/cuda-12.2/lib64/:$LD_LIBRARY_PATH"

[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env" # Rust
[ -f "$HOME/.ghcup/env" ] && . "$HOME/.ghcup/env" # Haskell
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)" # make less more friendly for non-text input files, see lesspipe(1)

get() {  # my custom command to copy paths of files and folders to clipboard using fuzy finding
  find "${2:-'.'}" -name ".*" | fzf -m -1 -q "${1:-''}" | tr '\n' ' ' | clip.exe
}
